apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-demo
  template:
    metadata:
      labels:
        app: eks-demo
    spec:
      containers:
      - name: eks-demo
        image: <your-account-id>.dkr.ecr.us-east-1.amazonaws.com/eks-demo:latest
        ports:
        - containerPort: 80

